### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by dcsan** [meteoric/meteorhunt#11]
crashes on boot

```
ERR) TypeError: Cannot read property 'clientId' of undefined
W20150207-14:18:44.129(-8)? (STDERR)     at Accounts.onCreateUser.user.emails (app/server/accounts.js:5:46)
W20150207-14:18:44.129(-8)? (STDERR)     at /Users/dc/dev/ref/meteorhunt/.meteor/local/build/programs/server/boot.js:182:5
```

![image](https://cloud.githubusercontent.com/assets/514002/6094188/501a15a8-aed4-11e4-952d-e6aef509d540.png)

**Comment by olivier-w** [comment]
Getting the same error here :(

**Comment by jeangui** [comment]
the same for me.

regards
@jeangui

**Comment by dcsan** [comment]
you should check out the demo of all widgets app
https://github.com/meteoric/demo

this seems to be better maintained.

**Comment by nickw** [comment]
Actually that one is the most outdated- I recently updated both meteorhunt and contacts

**Comment by sajjadakhter** [comment]
i noticed similar error unless i use meteor --settings settings.json

**Comment by jeangui** [comment]
You are right `meteor --settings settings.json` works fine. :+1: 
Now when I want to run thé application into thé IOS Simulator by running thé following command:
`meteor run ios --settings settings.json` .It does not work. The same error again. How do you include the settings in thé ios build ?

Have you an idea of what command line I should use instead ?

thanks.

**Comment by dcsan** [comment]
i think there's a separate settings for cordova. check meteor docs

**Comment by mountainash** [comment]
`meteor run ios --settings settings.json` worked for me.
You've edited settings.json right with details created at https://www.meteor.com/account-settings/apps right?

Note: I've patched to use Meteor 1.0.3.

**Comment by jeangui** [comment]
Hi

Thanks for your help.
I did create an app in the meteor developper console.
And then i filled the settings.json with the correct info coming from the console.
Still not working.

Regards.
jeangui

**Comment by JanAhrend** [comment]
running 
meteor --settings settings.json 
worked for me.
